# Generated by Django 5.1.6 on 2025-03-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sanduiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sanduiche')),
                ('descricao', models.TextField(help_text='Descreva os ingredientes e caracteristicas do sanduiche.', verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor do sanduiche em R$', max_digits=10, verbose_name='Preço')),
                ('emPromocao', models.BooleanField(default=False, help_text='Marque se está em promoção', verbose_name='Em promoção')),
                ('imagem', models.ImageField(help_text='Faça o upload da imagem do sanduiche.', upload_to='media/', verbose_name='Imagem do sanduiche')),
            ],
        ),
        migrations.CreateModel(
            name='InfoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.PositiveIntegerField(verbose_name='Calorias (kcal)')),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proteinas (g)')),
                ('gorduras', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gorduras (g)')),
                ('carboidratos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carboidratos (g)')),
                ('gorduras_saturadas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gorduras saturadas (g)')),
                ('gorduras_trans', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gorduras Trans (g)')),
                ('sodio', models.PositiveIntegerField(verbose_name='Sódio (mg)')),
                ('sanduiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Burgueria.sanduiche')),
            ],
        ),
    ]
